// Generated by CoffeeScript 1.10.0
(function() {
  var routes;

  routes = function($routeProvider) {
    return $routeProvider.when('/login', {
      templateUrl: 'partials/login.jade'
    }).when('/register', {
      templateUrl: 'partials/register.jade'
    }).when('/', {
      templateUrl: 'partials/index.jade'
    }).otherwise({
      redirectTo: '/'
    });
  };

  client.config(['$routeProvider', routes]);

}).call(this);

//# sourceMappingURL=routes.js.map
