// Generated by CoffeeScript 1.10.0
(function() {
  var TokenService;

  TokenService = (function() {
    function TokenService(localStorageService) {
      this.localStorageService = localStorageService;
      this.token_key = 'token';
    }

    TokenService.prototype.save = function(token) {
      return this.localStorageService.set(this.token_key, token);
    };

    TokenService.prototype.get = function() {
      return this.localStorageService.get(this.token_key);
    };

    TokenService.prototype["delete"] = function() {
      return this.localStorageService.remove(this.token_key);
    };

    TokenService.prototype.payload = function() {
      var payload, token;
      token = this.get();
      payload = atob(token.split('.')[1]);
      return JSON.parse(payload);
    };

    return TokenService;

  })();

  client.service('token_service', TokenService);

}).call(this);

//# sourceMappingURL=token_service.js.map
